### ISSUE TITLE
Logistische Regressionen 

### ISSUE THREAD

**Issue by merve-sv** [ablaette/incivility#5]
1) Diskussion: Reichen uns nicht 3 Modelle? 
Modell B 
Modell D 
Modell E
Würde auf A verzichten, da dort die Kontrollvariablen nicht enthalten sind und auf C verzichten, weil es nur zwei Variablen enthält, die unsystematisch sind.  

2) Racialised (britsche Schreibweise) 

3) **WICHTIG:** Kodierung und Richtung der Variable für die deskriptive Repräsentation prüfen. Hier steht noch "certainty to stay"

**Comment by ablaette** [comment]
Die Tabellen sehen jetzt so aus:

<img width="782" alt="grafik" src="https://github.com/ablaette/incivility/assets/6830901/ce562cf9-8d2a-43a8-a983-8ac6d30fad10">

<img width="800" alt="grafik" src="https://github.com/ablaette/incivility/assets/6830901/fd06d7b0-0301-48ee-8760-cb511650f446">

Die britische Schreibweise ("racialised") habe ich noch nicht umgesetzt, weil ich dafür in allen Skripten suchen und ersetzen muss - kann ich noch machen, aber das mache ich besser mit frischem Kopf. 

Wichtig zur Richtung der Variablen: Wir erklären (a) certainty to stay und (b) avoiding topics. Die Richtungen der Effekte sind da unterschiedlich, was vielleicht verwirrend sein mag. Aber wir haben uns für "stay" entschieden, weil die die missings bei der exit-Variable eine Unsicherheit ausdrücken, die inhaltlich relevant ist. 

Ich würde die Unterschiedlichkeit der Richtungen als Komplexität sehen, die vermittelbar und der Sache angemessen ist. Es sei denn, es gibt eine gute Lösung?

**Comment by merve-sv** [comment]
zu a) certainty to stay: 
Alles klar - dann stellen wir jetzt wieder alles um :) - so wie es anfangs war.
